// Re-exporta ícones Hugeicons para uso conveniente
// Documentação: https://hugeicons.com/

export {
  AlertCircleIcon,
  Home01Icon,
  Search01Icon,
  User02Icon,
  Wallet01Icon,
  MoneyExchange03Icon,
  ChartLineData01Icon,
  ArrowRight01Icon,
  ArrowUpRight01Icon,
  ArrowLeft01Icon,
  PanelLeftCloseIcon,
  PanelLeftOpenIcon,
  Add01Icon,
  Edit01Icon,
  Delete01Icon,
  Settings01Icon,
  DashboardSquare01Icon,
  Calendar01Icon,
  BarChartIcon,
  Target01Icon,
  CreditCardIcon,
  Invoice01Icon,
  Logout01Icon,
  LockedIcon,
  CircleLock01Icon,
  CircleUnlock01Icon,
  Tag01Icon,
  ArrowDown01Icon,
  Message01Icon,
  Tick01Icon,
  School01Icon,
  Tv01Icon,
  Menu01Icon,
} from "@hugeicons/core-free-icons";
